version: '3'
services:
  graphWeb:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: 127.0.0.1:4000/staging-graphWeb:latest
    ports:
      - "4001:5000"
    environment:
      - "SERVICE_NAME=graphWeb"
      - "SERVICE_TAGS=main"
      - "ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}"
    deploy:
      mode: replicated
      replicas: 1

networks:
  default:
    external:
      name: mongo_network
